const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n||0));let store,editing=null;
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
function slugify(s){return String(s||'workshop').trim().toLowerCase().replace(/[^a-z0-9\u3040-\u30ff\u3400-\u9fff]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36)}
(async()=>{store=await RSStore.get();if(store.mode==='live'){modebar.classList.remove('demo');modebar.textContent='LIVE｜Supabaseオンライン管理'}const user=await store.currentUser();if(user)openAdmin();})();
loginForm.onsubmit=async e=>{e.preventDefault();try{await store.signIn(loginEmail.value,loginPassword.value);openAdmin()}catch(err){toast(err.message||'ログインできません')}};
async function openAdmin(){loginView.classList.add('hidden');adminView.classList.remove('hidden');await renderDashboard()}
logoutBtn.onclick=async()=>{await store.signOut();adminView.classList.add('hidden');loginView.classList.remove('hidden')};dashboardBtn.onclick=()=>showPane('dashboard');reservationsBtn.onclick=async()=>{showPane('reservations');await renderReservations()};newEventBtn.onclick=()=>openEditor();
function showPane(name){dashboardPane.classList.toggle('hidden',name!=='dashboard');editorPane.classList.toggle('hidden',name!=='editor');reservationsPane.classList.toggle('hidden',name!=='reservations')}
function instructorUrl(token){const url=new URL('../instructor/',location.href);url.searchParams.set('token',token);return url.href}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{return false}}
async function openInstructorView(eventId){const win=window.open('about:blank','_blank');if(win)win.opener=null;try{const token=await store.getInstructorToken(eventId);const url=instructorUrl(token);await copyText(url);if(win)win.location.href=url;else location.href=url;toast('講師ページを開きました。共有URLもコピーしました')}catch(err){if(win)win.close();toast(err.message||'講師ページを作成できません')}}
async function rotateInstructorView(eventId){if(!confirm('現在の講師共有URLを無効にして、新しいURLを発行しますか？'))return;try{const token=await store.rotateInstructorToken(eventId);const url=instructorUrl(token);const copied=await copyText(url);toast(copied?'新しい講師URLをコピーしました':'新しい講師URLを発行しました');if(!copied)prompt('このURLを講師へ共有してください',url)}catch(err){toast(err.message||'講師URLを再発行できません')}}
async function renderDashboard(){showPane('dashboard');const events=await store.listEvents();const reservations=await store.listReservations();const active=reservations.filter(r=>r.status!=='cancelled');const revenue=active.reduce((a,r)=>a+Number(r.amount||0),0),paid=active.filter(r=>r.paymentStatus==='paid').reduce((a,r)=>a+Number(r.amount||0),0);stats.innerHTML=`<div class="stat"><span>イベント</span><strong>${events.length}</strong></div><div class="stat"><span>有効予約</span><strong>${active.length}</strong></div><div class="stat"><span>売上見込</span><strong>${yen(revenue)}</strong></div><div class="stat"><span>入金済</span><strong>${yen(paid)}</strong></div>`;adminEvents.innerHTML=events.length?events.map(e=>`<article class="event-card"><div class="event-cover">${e.cover?`<img src="${e.cover}" alt="">`:'RHYTHM SPEAKER'}</div><div class="event-body"><span class="badge ${e.status==='published'?'live':'draft'}">${e.status==='published'?'公開中':'下書き'}</span><h2>${esc(e.title)}</h2><div class="meta">${esc(e.date)} / ${esc(e.venue)}</div><div class="toolbar"><button class="smallbtn" data-edit="${e.id}">編集</button><button class="smallbtn" data-res="${e.id}">予約</button><button class="smallbtn" data-instructor="${e.id}">講師ページ</button><button class="smallbtn" data-rotate-instructor="${e.id}">講師URL再発行</button><button class="smallbtn" data-copy="${e.id}">複製</button><button class="smallbtn danger" data-del="${e.id}">削除</button></div></div></article>`).join(''):'<div class="empty">イベントがありません。「＋ 新しいイベント」から作成してください。</div>';$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));$$('[data-res]').forEach(b=>b.onclick=async()=>{showPane('reservations');await renderReservations(b.dataset.res)});$$('[data-instructor]').forEach(b=>b.onclick=()=>openInstructorView(b.dataset.instructor));$$('[data-rotate-instructor]').forEach(b=>b.onclick=()=>rotateInstructorView(b.dataset.rotateInstructor));$$('[data-copy]').forEach(b=>b.onclick=async()=>{await store.duplicateEvent(b.dataset.copy);toast('イベントを複製しました');renderDashboard()});$$('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('このイベントを削除しますか？')){await store.deleteEvent(b.dataset.del);renderDashboard()}})}
function emptyEvent(){const id=crypto.randomUUID?crypto.randomUUID():'e'+Date.now();return{id,slug:'',title:'',instructor:'',date:'',venue:'池袋 リズムスピーカー',address:'東京都豊島区西池袋3-22-10 大晃第7ビル B1',summary:'',description:'',status:'draft',cover:'',paymentNote:'',sessions:[]}}
async function openEditor(id){showPane('editor');editing=id?(await store.listEvents()).find(e=>e.id===id):emptyEvent();renderEditor()}
function renderEditor(){editorPane.innerHTML=`<div class="row mobile-stack"><div><p class="eyebrow">EVENT EDITOR</p><h1>${editing.title?esc(editing.title):'新しいイベント'}</h1></div><button class="btn subtle" id="backBtn">戻る</button></div><form id="eventForm" class="panel" style="margin-top:18px"><div class="grid2"><label>タイトル<input id="eTitle" required value="${esc(editing.title)}"></label><label>講師名<input id="eInstructor" value="${esc(editing.instructor)}"></label></div><div class="grid2"><label>開催日<input id="eDate" type="date" required value="${esc(editing.date)}"></label><label>公開状態<select id="eStatus"><option value="draft" ${editing.status==='draft'?'selected':''}>下書き</option><option value="published" ${editing.status==='published'?'selected':''}>公開</option></select></label></div><label>会場<input id="eVenue" value="${esc(editing.venue)}"></label><label>住所<input id="eAddress" value="${esc(editing.address)}"></label><label>短い説明<input id="eSummary" value="${esc(editing.summary)}"></label><label>詳細<textarea id="eDescription" rows="4">${esc(editing.description)}</textarea></label><label>フライヤー / 写真<input id="eCoverFile" type="file" accept="image/*"><span class="help">スマホの写真ライブラリから選択できます。</span>${editing.cover?`<img class="poster-preview" src="${editing.cover}" alt="">`:''}</label><label>支払い案内<input id="ePaymentNote" value="${esc(editing.paymentNote)}" placeholder="例：オンライン決済または当日支払い"></label><div class="divider"></div><div class="row"><h2 style="margin:0">クラス・商品</h2><button class="smallbtn" id="addSessionBtn" type="button">＋ クラス追加</button></div><div id="sessionEditor" class="sessions" style="margin-top:12px"></div><div class="divider"></div><button class="btn full" type="submit">保存する</button></form>`;backBtn.onclick=renderDashboard;addSessionBtn.onclick=()=>{editing.sessions.push({id:crypto.randomUUID?crypto.randomUUID():'s'+Date.now(),name:'新しいクラス',start:'',end:'',minutes:60,price:3500,capacity:10,level:'',paymentUrl:'',consumes:[]});renderSessions()};eventForm.onsubmit=saveEditor;renderSessions()}
function renderSessions(){
  sessionEditor.innerHTML=editing.sessions.length?editing.sessions.map((s,i)=>`<article class="session-card" data-si="${i}">
    <div class="row"><strong>クラス ${i+1}</strong><button class="smallbtn danger" type="button" data-rm="${i}">削除</button></div>
    <div class="grid2"><label>名称<input data-k="name" value="${esc(s.name)}"></label><label>レベル<input data-k="level" value="${esc(s.level)}"></label></div>
    <div class="grid3"><label>開始<input data-k="start" type="time" value="${esc(s.start)}"></label><label>終了<input data-k="end" type="time" value="${esc(s.end)}"></label><label>分数<input data-k="minutes" type="number" min="0" value="${Number(s.minutes||0)}"></label></div>
    <div class="grid2"><label>料金<input data-k="price" type="number" min="0" value="${Number(s.price||0)}"></label><label>定員<input data-k="capacity" type="number" min="1" value="${Number(s.capacity||10)}"></label></div>
    <label>オンライン支払いURL<input data-k="paymentUrl" type="url" value="${esc(s.paymentUrl||'')}" placeholder="Stripe / STORES等の決済URL"></label>
    <div><strong>セット商品の対象クラス</strong><div class="help">通常クラスは何も選びません。セット商品だけ、同時に席を消費するクラスを選択します。</div><div class="toolbar">${editing.sessions.filter((_,j)=>j!==i).map(other=>`<label class="checkline" style="margin:0"><input type="checkbox" data-consume="${i}" value="${other.id}" ${(s.consumes||[]).includes(other.id)?'checked':''}><span>${esc(other.name)}</span></label>`).join('')||'<span class="help">対象候補なし</span>'}</div></div>
  </article>`).join(''):'<div class="empty">クラスがありません。「＋ クラス追加」で作成してください。</div>';
  sessionEditor.querySelectorAll('[data-si]').forEach(card=>{const i=Number(card.dataset.si);card.querySelectorAll('[data-k]').forEach(inp=>inp.oninput=()=>{const k=inp.dataset.k;editing.sessions[i][k]=k==='price'||k==='capacity'||k==='minutes'?Number(inp.value):inp.value})});
  $$('[data-consume]').forEach(cb=>cb.onchange=()=>{const i=Number(cb.dataset.consume);const set=new Set(editing.sessions[i].consumes||[]);cb.checked?set.add(cb.value):set.delete(cb.value);editing.sessions[i].consumes=[...set]});
  $$('[data-rm]').forEach(b=>b.onclick=()=>{const removed=editing.sessions[Number(b.dataset.rm)]?.id;editing.sessions.splice(Number(b.dataset.rm),1);editing.sessions.forEach(s=>s.consumes=(s.consumes||[]).filter(x=>x!==removed));renderSessions()});
}
async function saveEditor(e){e.preventDefault();try{editing.title=eTitle.value.trim();editing.slug=editing.slug||slugify(editing.title);editing.instructor=eInstructor.value.trim();editing.date=eDate.value;editing.status=eStatus.value;editing.venue=eVenue.value.trim();editing.address=eAddress.value.trim();editing.summary=eSummary.value.trim();editing.description=eDescription.value.trim();editing.paymentNote=ePaymentNote.value.trim();if(eCoverFile.files[0])editing.cover=await store.uploadCover(eCoverFile.files[0]);if(!editing.sessions.length)throw new Error('クラスを1つ以上追加してください');await store.saveEvent(editing);toast('保存しました');await renderDashboard()}catch(err){toast(err.message||'保存できませんでした')}}
async function renderReservations(eventId=''){showPane('reservations');const allEvents=await store.listEvents();const rows=await store.listReservations(eventId||undefined);const ev=eventId?allEvents.find(e=>e.id===eventId):null;reservationsPane.innerHTML=`<div class="row mobile-stack"><div><p class="eyebrow">RESERVATIONS</p><h1>${ev?esc(ev.title):'全予約'}</h1></div><button class="btn subtle" id="resBack">戻る</button></div><div class="stats" style="margin:18px 0"><div class="stat"><span>予約</span><strong>${rows.filter(r=>r.status!=='cancelled').length}</strong></div><div class="stat"><span>入金済</span><strong>${yen(rows.filter(r=>r.status!=='cancelled'&&r.paymentStatus==='paid').reduce((a,r)=>a+Number(r.amount||0),0))}</strong></div><div class="stat"><span>未入金</span><strong>${rows.filter(r=>r.status!=='cancelled'&&r.paymentStatus!=='paid').length}</strong></div><div class="stat"><span>受付済</span><strong>${rows.filter(r=>r.status!=='cancelled'&&r.checkin).length}</strong></div></div><div class="tablewrap"><table><thead><tr><th>氏名</th><th>クラス</th><th>金額</th><th>支払</th><th>受付</th><th>状態</th><th>操作</th></tr></thead><tbody>${rows.length?rows.map(r=>{const e=allEvents.find(x=>x.id===r.eventId),s=e?.sessions.find(x=>x.id===r.sessionId);return`<tr><td><strong>${esc(r.name)}</strong><br><span class="help">${esc(r.email)}</span></td><td>${esc(s?.name||r.sessionId)}</td><td>${yen(r.amount)}</td><td class="${r.paymentStatus==='paid'?'kpi-ok':'kpi-warn'}">${r.paymentStatus==='paid'?'入金済':'未入金'}</td><td>${r.checkin?'受付済':'未受付'}</td><td>${r.status==='cancelled'?'取消':'予約'}</td><td>${r.status!=='cancelled'?`<button class="smallbtn" data-pay="${r.id}">${r.paymentStatus==='paid'?'未入金へ':'入金済へ'}</button> <button class="smallbtn" data-check="${r.id}">${r.checkin?'受付取消':'受付する'}</button> <button class="smallbtn danger" data-cancel="${r.id}">取消</button>`:''}</td></tr>`}).join(''):'<tr><td colspan="7">予約はありません。</td></tr>'}</tbody></table></div>`;resBack.onclick=renderDashboard;$$('[data-pay]').forEach(b=>b.onclick=async()=>{const r=rows.find(x=>x.id===b.dataset.pay);await store.updateReservation(r.id,{paymentStatus:r.paymentStatus==='paid'?'unpaid':'paid'});renderReservations(eventId)});$$('[data-check]').forEach(b=>b.onclick=async()=>{const r=rows.find(x=>x.id===b.dataset.check);await store.updateReservation(r.id,{checkin:!r.checkin});renderReservations(eventId)});$$('[data-cancel]').forEach(b=>b.onclick=async()=>{if(confirm('予約をキャンセルしますか？')){await store.updateReservation(b.dataset.cancel,{status:'cancelled'});renderReservations(eventId)}})}
